language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alsaheem/multi-docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alsaheem/multi-docker-react npm run test

after_success:
  - docker build -t alsaheem/multi-docker-client ./client
  - docker build -t alsaheem/multi-docker-nginx ./nginx
  - docker build -t alsaheem/multi-docker-server ./server
  - docker build -t alsaheem/multi-worker-server ./worker
  # login to docker
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  #push images to dockerhub
  - docker-push alsaheem/multi-docker-client
  - docker-push alsaheem/multi-docker-nginx
  - docker-push alsaheem/multi-docker-server
  - docker-push alsaheem/multi-docker-worker

